[build]
  publish = "kairoslab/public"
  command = "hugo --gc --themesDir themes/cupper-hugo-theme"

[build.environment]
  HUGO_VERSION = "v0.73.0-428907CC windows/amd64"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://cupper-hugo-theme.netlify.com/"
  

[context.production.environment]
HUGO_VERSION = "0.73.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.73.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.73.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.73.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
